image: hackerstanislav/servant:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
before_script:
  - npm install
  - npm run servant -- install
stages:
  - validate
  - build
  - tests
validate:
  stage: validate
  script:
    - npm run servant -- validate
build:
  stage: build
  script:
    - npm run servant -- clean build
tests:
  stage: tests
  script:
    - npm run servant -- clean build tests
